# Generated by Django 4.0.5 on 2022-06-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('Easy', 'Easy'), ('Hard', 'Hard'), ('Usual', 'Usual')], max_length=15)),
                ('type', models.CharField(choices=[('PreLegend', 'PreLegend'), ('Legend', 'Legend'), ('Repeat Legend', 'Repeat Legend'), ('Lower A', 'Lower A'), ('Lower B', 'Lower B'), ('Upper A', 'Upper A'), ('Warning', 'Warning'), ('Paired A', 'Paired A'), ('Paired B', 'Paired B')], max_length=50)),
                ('aircraft', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('Finished', 'Finished'), ('In progress', 'In progress'), ('Kickback', 'Kickback'), ('Started', 'Started'), ('Suspend', 'Suspend')], max_length=50)),
                ('errors_count', models.IntegerField(default=0)),
                ('info_count', models.IntegerField(default=0)),
            ],
        ),
    ]
